services:
    security.authentication.factory.persona:
        class:  AHS\PersonaBundle\DependencyInjection\Security\Factory\PersonaFactory
        tags:
            - { name: security.listener.factory }