services:
    security.authentication.factory.browserid:
        class:  FWM\BrowserIDBundle\DependencyInjection\Security\Factory\BrowserIDFactory
        tags:
            - { name: security.listener.factory }