services:
  persona.security.authentication.provider:
    class:  AHS\PersonaBundle\Security\Authentication\Provider\PersonaProvider
    arguments: ['']

  persona.security.authentication.listener:
    class:  AHS\PersonaBundle\Security\Firewall\PersonaListener
    arguments: [@security.context, @security.authentication.manager]